"""
WAF detector — identify Web Application Firewall from response patterns.
"""

from hermes.tools.registry import tool, ToolCategory


WAF_SIGNATURES: dict[str, dict] = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "__cfduid"],
        "status_codes": [],
        "response_patterns": ["cloudflare-nginx", "cf-chl-", "Attention Required! | Cloudflare"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amz-cf-pop"],
        "status_codes": [],
        "response_patterns": ["Request blocked.", "AWS WAF"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-akamai-request-id"],
        "status_codes": [],
        "response_patterns": ["Reference #", "akamai"],
    },
    "CloudFront": {
        "headers": ["x-cache", "x-amz-cf-id"],
        "status_codes": [],
        "response_patterns": ["Generated by cloudfront"],
    },
    "ModSecurity": {
        "headers": [],
        "status_codes": [403, 406],
        "response_patterns": ["ModSecurity", "This error was generated by Mod_Security", "Not Acceptable!"],
    },
    "F5 BIG-IP": {
        "headers": ["x-wa-info"],
        "status_codes": [],
        "response_patterns": ["The requested URL was rejected", "BIG-IP"],
    },
    "Imperva/Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "status_codes": [],
        "response_patterns": ["Incident ID:", "_Incapsula_Resource"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "status_codes": [],
        "response_patterns": ["Sucuri WebSite Firewall", "Access Denied - Sucuri"],
    },
    "Fortinet/FortiWeb": {
        "headers": [],
        "status_codes": [403],
        "response_patterns": ["FortiWeb", "Application Firewall"],
    },
    "Barracuda": {
        "headers": [],
        "status_codes": [],
        "response_patterns": ["Barracuda", "because your activity was suspicious"],
    },
}


@tool(
    name="detect_waf",
    category=ToolCategory.ANALYSIS,
    agent="artemis",
    description="Detect WAF/CDN from HTTP response headers and body",
    tags=["analysis", "waf", "cdn", "detection"],
)
def detect_waf(
    response_data: list[dict],  # [{"url": "...", "headers": {...}, "body": "...", "status": N}, ...]
) -> dict:
    """Detect Web Application Firewalls from HTTP responses."""
    results = {}

    for resp in response_data:
        url = resp.get("url", "unknown")
        headers = {k.lower(): str(v) for k, v in resp.get("headers", {}).items()}
        body = resp.get("body", "").lower()
        status = resp.get("status", 0)

        detected = []

        for waf_name, sig in WAF_SIGNATURES.items():
            matched = False

            # Header check
            for sig_header in sig["headers"]:
                if sig_header in headers:
                    matched = True
                    break

            # Status code check
            if not matched and status in sig["status_codes"]:
                matched = True

            # Response body check
            if not matched:
                for pattern in sig["response_patterns"]:
                    if pattern.lower() in body:
                        matched = True
                        break

            if matched:
                detected.append(waf_name)

        results[url] = {
            "wafs": detected,
            "has_waf": len(detected) > 0,
            "waf_count": len(detected),
        }

    all_wafs = set()
    for r in results.values():
        all_wafs.update(r["wafs"])

    return {
        "endpoints_checked": len(response_data),
        "results": results,
        "detected_wafs": sorted(all_wafs),
    }
